### ISSUE TITLE
Kein Heal nach Kill

### ISSUE THREAD

**Issue by ghost** [A3ReallifeRPG/GunGame_Nordholm#1]
Nach einem Kill wird man nicht mehr geheilt.
Das Problem ist in der [fn_killProcessor.sqf](https://github.com/A3ReallifeRPG/GunGame_Nordholm/blob/master/bin/client/fn_killProcessor.sqf) Datei. Die Zeile `[objNull, player] call ace_medical_fnc_treatmentAdvanced_fullHealLocal;` muss nach dem ACE Medical Update durch `[player] call ace_medical_treatment_fnc_fullHealLocal` ausgetauscht werden.

**Comment by M4I3X** [comment]
Fehler ist bereits bekannt, sollte Zeitnah behoben sein.
